sudo: required
services:
  - docker

before_install:
  - docker build -t stfrassetto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stfrassetto/react-test npm test

after_success:
  # Build production images.
  - docker build -t stfrassetto/multi-client ./client
  - docker build -t stfrassetto/multi-nginx ./nginx
  - docker build -t stfrassetto/multi-server ./server
  - docker build -t stfrassetto/multi-worker ./worker
  # Log in to the docker CLI.
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take those images and push them to the docker HUB.
  - docker push stfrassetto/multi-client
  - docker push stfrassetto/multi-nginx
  - docker push stfrassetto/multi-server
  - docker push stfrassetto/multi-worker
